config/routes.rb
Tinytalk::Application.routes.draw do

  resources :comments, only: [:create, :edit, :update, :destroy]

  devise_for :users

  root to: "home#signin"

  match "index", to: "home#index"

  put "/update", to: "home#update"

  match 'boards/remove_user_from_board/:board_id/:user_id' => 'boards#remove_user_from_board'

  resources :boards do
    resources :pins
    resources :text_pins
    resources :links
    resources :quotes
  end

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :author, :board_id, :note, :quote, :user_id

  belongs_to :user
  belongs_to :board

  validates :quote, presence: true
  validates :author, presence: true
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  # GET /quotes
  # GET /quotes.json
  def index
    @board= Board.find(params[:board_id])
    @quotes = @board.quotes.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quotes }
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @quote = Quote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/new
  # GET /quotes/new.json
  def new
    @board = Board.find(params[:board_id])
    @quote = current_user.quotes.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/1/edit
  def edit
    @quote = Quote.find(params[:id])
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = current_user.quotes.create(params[:quote])

    respond_to do |format|
      if @quote.save
        format.html { redirect_to "/boards/#{@quote.board_id}", notice: 'Quote was successfully created.' }
        format.json { render json: @quote, status: :created, location: @quote }
      else
        format.html { render action: "new" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quotes/1
  # PUT /quotes/1.json
  def update
    @quote = Quote.find(params[:id])

    respond_to do |format|
      if @quote.update_attributes(params[:quote])
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<div id="main-container">
    <div class="container">

      <div class="span4">

        <!-- Page Title -->
        <div class="page-heading">
          <h1>Add Link</h1>
        </div>

          <!-- Alerts -->
          <div class="entry drop-shadow curved">
            <div class="contact-alerts">
        </div>


          <div class="row-fluid">
            <div class="span12">
              <%= simple_form_for([@board, @quote]) do |f| %>
                <%= f.error_notification %>
                <div class="form-inputs">
                  <%= f.input :quote %>
                  <%= f.input :author %>
                  <%= f.input :note %>
                  <%= f.hidden_field :board_id, value: @board.id %>
                </div>
                <div class="form-actions">
                  <%= f.button :submit,:html => {:class => 'contact-submit'} %>
                </div>
              <% end %>
            </div>
            <%= link_to 'Back', board_path(@board) %>
          </div>
      </div>
    </div>
  </div>

app/views/quotes/_quote.html.erb
<div class="isotope-post quote span4">
  <div>
    <!-- Quote -->
    <div class="entry-quote">
      <blockquote><p><%=quote.quote %></p></blockquote>
    </div>

      <div class="entry drop-shadow curved ">
        <!-- Title -->
        <h5 class="heading">
          <a href="#"><%= quote.author %></a>
        </h5>

        <!-- Content -->
        <p><%= quote.note %></p>
        <div class="clearboth"></div>

        <!-- Meta -->
        <ul class="entry-meta">
          <li class="time">2 Days ago</li>
        </ul>

    </div>

  </div>
</div>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<h1>Listing quotes</h1>

<table>
  <tr>
    <th>Quote</th>
    <th>Author</th>
    <th>Note</th>
    <th>User</th>
    <th>Board</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @quotes.each do |quote| %>
  <tr>
    <td><%= quote.quote %></td>
    <td><%= quote.author %></td>
    <td><%= quote.note %></td>
    <td><%= quote.user_id %></td>
    <td><%= quote.board_id %></td>
    <td><%= link_to 'Show', quote %></td>
    <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
    <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Quote:</b>
  <%= @quote.quote %>
</p>

<p>
  <b>Author:</b>
  <%= @quote.author %>
</p>

<p>
  <b>Note:</b>
  <%= @quote.note %>
</p>

<p>
  <b>User:</b>
  <%= @quote.user_id %>
</p>

<p>
  <b>Board:</b>
  <%= @quote.board_id %>
</p>


<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>