config/routes.rb
Tinytalk::Application.routes.draw do

  resources :comments, only: [:create, :edit, :update, :destroy]

  devise_for :users

  root to: "home#signin"

  match "index", to: "home#index"

  put "/update", to: "home#update"

  match 'boards/remove_user_from_board/:board_id/:user_id' => 'boards#remove_user_from_board'

  resources :boards do
    resources :pins
    resources :text_pins
    resources :links
    resources :quotes
  end

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :board_id

  belongs_to :user
  belongs_to :board
  has_attached_file :image, styles: {medium: "320x240"}

  validates :description, presence: true
  validates :user_id, presence: true
  validates_attachment :image, presence:true,
                      content_type: {content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
                      size: {less_than: 5.megabytes }


end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  # GET /pins
  # GET /pins.json
  def index
    @board= Board.find(params[:board_id])
    @pins = @board.pins.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @user = current_user
    @pin = Pin.find(params[:id])
    @board = Board.find(params[:board_id])
    @comment = Comment.new
    @comments = Comment.where(commentable_type: Pin, commentable_id: @pin)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @board = Board.find(params[:board_id])
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @board = Board.find(params[:board_id])
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create

    @pin = current_user.pins.create(params[:pin])


    respond_to do |format|
      if @pin.save
        format.html { redirect_to "/boards/#{@pin.board_id}", notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @board = Board.find(params[:board_id])
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to board_pin_path(@board, @pin), notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @board = params[:board_id]
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to board_path(@board)}
      format.json { head :no_content }
    end
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<div id="main-container">
    <div class="container">

      <div class="span4">

        <!-- Page Title -->
        <div class="page-heading">
          <h1>Add a Photo</h1>
        </div>

          <!-- Alerts -->
          <div class="entry drop-shadow curved">
            <div class="contact-alerts">
        </div>
        <div class="row-fluid">
            <div class="span12">
<%= simple_form_for([@board, @pin]) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>


  <div class="form-inputs">
    <%= f.input :image, label: "Upload an Image" %>
    <%= f.input :description, as: :text, input_html:{rows: "3"} %>
    <%= f.hidden_field :board_id, value: @board.id %>
  </div>

  <div class="form-actions">
    <br>
    <%= f.button :submit %>
  </div>
<% end %>
</div>
<%= link_to 'Back', board_path(@board) %>
          </div>
      </div>
    </div>
  </div>

app/views/pins/_pin.html.erb
<div class="isotope-post span4 image">
        <div>

          <!-- Thumbnail -->


          <a href="<%=pin.image %>" class="fancybox entry-image">
            <span class="entry-image-overlay"></span>
            <img src="<%=pin.image %>" alt="" />
          </a>

            <div class="entry drop-shadow curved">

              <!-- Title -->
              <h1 class="heading">
                <%= pin.user.email %>
              </h1>

              <!-- Content -->
              <p><%=pin.description %></p>
              <!-- Meta -->
              <ul class="entry-meta">
                <li class="time">
                  <%= link_to "View Comments", board_pin_path(pin.board_id,pin.id)%>
                  (<%= Comment.where(commentable_type: "Pin", commentable_id: "#{pin.id}").length %>)
                </li>
              </ul>

          </div>

        </div>
      </div>






<%
=begin %>
<div class="box">
    <%= link_to (image_tag pin.image(:medium)), board_pin_path(@board, pin) %>
    <p class="description">
    <%= pin.description %>
    </p>
    <p>
      <strong>
        Posted by <%= pin.user.email %>
      </strong>
    </p>

    <% if current_user == pin.user %>
      <p>
        <%= link_to 'Edit', edit_board_pin_path(@board,pin) %>
        <%= link_to 'Destroy', board_pin_path(@board,pin), method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>


    <input type="checkbox" id="p" name="check_all_1" title="Select All" onclick="this.parentNode.style.backgroundColor='red';">
</div>
<%
=end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Back', board_pin_path(@board, @pin) %>

app/views/pins/index.html.erb
<%= render 'home/signin' %>

<div id ="pins">
<% @pins.each do |pin| %>
  <div class="box">
      <%= image_tag pin.image(:medium) %>
      <p class="description">
      <%= pin.description %>
      </p>
      <p>
        <strong>
          Posted by <%= pin.user.email %>
        </strong>
      </p>
  </div>

<% end %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

app/views/pins/show.html.erb
<div class="preloader"></div>
  <div class="mobile-nav-container">

    <div class="mobile-nav-bar">

        <button type="button" class="btn-mobile-nav" data-toggle="collapse" data-target="#mobile-nav"></button>

      <!-- Mobile Logo -->
      <div class="logo-image">
        <a>
          <img src="<%= @user.avatar.url %>" alt=""/>
        </a>
      </div>

    </div>

    <!-- Mobile Drop Down -->
    <div id="mobile-nav" class="collapse">
      <ul>
         <li><%= link_to "All Boards", root_path %><br></li>
          <li class="dropdown"><a href="#">Add Pin</a>
            <ul class="sub-menu">
              <li><%= link_to "Add Image", new_board_pin_path(@board, @pin) %></li>
              <li><%= link_to "Add Text", new_board_text_pin_path(@board, @pin) %></li>
            </ul>
          </li>
            <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>
  <!-- END Mobile Navigation -->

  <!-- BEGIN Side Nav -->
  <div class="side-nav">

    <!-- Side Nav Logo -->
    <div class="side-nav-logo">
      <a href="/">
        <img src="<%= @user.avatar.url %>" class="img-circle" alt=""/>
      </a>
    </div>

    <!-- Side Nav Text -->
    <div class="side-nav-bio">
      <h2><strong>Board:</strong><%= @board.title %></h2>
    </div>

    <!-- Side Nav Menu -->
    <ul class="side-nav-menu">
      <li><%= link_to "Back", board_path(@board) %><br></li>
      <li class="dropdown"><a href="#">Add Pin</a>
        <ul class="sub-menu">
          <li><%= link_to "Add Image", new_board_pin_path(@board, @pin) %></li>
          <li><%= link_to "Add Text", new_board_text_pin_path(@board, @pin) %></li>
        </ul>
      </li>
        <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
    </ul>

    <!-- Side Nav Widgets -->
    <div class="side-nav-widget">
      <div class="side-nav-widget-inner">
        <ul>
          <li class="widget widget_search">
            <form role="search" method="get" id="searchform" action="#">
                <input type="text" placeholder="Search" value="" name="s" id="s" />
                <input type="submit" id="searchsubmit" value="Search" />
            </form>
          </li>
        </ul>
      </div>
    </div>

    <!-- Side Nav Footer -->
    <div class="side-nav-footer">
    </div>

  </div>


<div id="main-container">
    <div class="container">

      <div class="row">
        <div class="span8 post-center">

          <!-- Image -->


          <%=image_tag(@pin.image,:class => "entry-image" )%>

            <div class="entry drop-shadow curved ">

              <!-- Title -->
              <h1 class="heading"><%=User.find(@pin.user_id).username %></h1>

              <!-- Content -->
              <p><%= @pin.description%></p>

              <!-- Comments -->
              <div id="allcomments">
              <ul class="entry-meta">
                <h2 class="heading">Comments</h2>
                <% @comments.each do |comment| %>
                  <li id="comment<%= comment.id %>">
                    <p>
                      <strong><%= User.find(comment.user_id).username %></strong>: <%= comment.content %>
                      <button data-id="<%= comment.id  %>" data-method="commdelete">Delete</button>
                    </p>
                  </li><br>
                <% end %>
              </ul>
              </div> <!-- Closing All Comments -->

              <!-- New Comments -->
              <%= form_for @comment do |f| %>
                <%= f.text_area :content, placeholder: "Enter Comment Here" %>
                <%= f.hidden_field :commentable_type, value: "Pin" %>
                <%= f.hidden_field :commentable_id, value: @pin.id %>
                <%= f.hidden_field :board_id, value: @board.id %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.submit 'Submit Comment', id: "commentsubmit" %>
              <% end %>

              <!-- Meta -->
              <ul class="entry-meta">
                <li class="time"><%=@pin.created_at %></li>
              </ul>

          </div>

        </div>
      </div>

    </div>
  </div>





<%
=begin %>
<p>
  <%=image_tag @pin.image(:medium) %>
  <b>Description:</b>
  <%= @pin.description %>
  <%= @pin.user.email %>
</p>
<div id="allcomments">
  <p>
    <% @comments.each do |comment| %>
      <p>
      <strong><%= User.find(comment.user_id).username %></strong>: <%= comment.content %>
      </p>
    <% end %>
  </p>
</div>
<%= form_for @comment do |f| %>
  <%= f.text_area :content, placeholder: "Enter Comment Here" %>
  <%= f.hidden_field :commentable_type, value: "Pin" %>
  <%= f.hidden_field :commentable_id, value: @pin.id %>
  <%= f.hidden_field :board_id, value: @board %>
  <%= f.submit 'Submit Comment', id: "commentsubmit" %>
<% end %>

<% if current_user == @pin.user %>
<%= link_to 'Edit', edit_board_pin_path(@board) %> |
<% end %>
<%= link_to 'Back', board_path(@board) %>

<br><br>
<%
=end %>