config/routes.rb
Tinytalk::Application.routes.draw do

  resources :comments, only: [:create, :edit, :update, :destroy]

  devise_for :users

  root to: "home#signin"

  match "index", to: "home#index"

  put "/update", to: "home#update"

  match 'boards/remove_user_from_board/:board_id/:user_id' => 'boards#remove_user_from_board'

  resources :boards do
    resources :pins
    resources :text_pins
    resources :links
    resources :quotes
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  attr_accessible :title, :user_id

  has_many :user_boards
  has_many :users, :through => :user_boards
  has_many :pins, dependent: :destroy

  has_many :text_pins, dependent: :destroy

  accepts_nested_attributes_for :users

  has_many :text_pins, dependent: :destroy
  has_many :links, dependent: :destroy
  has_many :quotes, dependent: :destroy


  validates :title, presence: :true
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def new
    @board = Board.new
  end

  def create
    @user = current_user

    @users = params[:board][:users].map do |username|
      User.find_by_username(username)
    end.compact

    if @users.present?
      @board = @user.boards.create(:title => params[:board][:title])
      @users.each do |user|
        @board.users << user
      end
    end

    render :json => {board: @board, users: @board.users}, status: 201
  end

   def show
    @board = Board.find(params[:id])
    @user = current_user
    @all = @board.pins + @board.text_pins + @board.links + @board.quotes
    @all.sort! {|a, b| b.created_at <=> a.created_at}
    @users = @board.users

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => {board: @board, users: @users}}
    end

  end

  def destroy
    Board.delete(params[:id])
    render text: "removed board" , status: 200
  end

  def remove_user_from_board
    board = Board.find(params[:board_id])
    board.users.delete(User.find(params[:user_id]))
    render text: "removed user" , status: 200
  end

  def update
    board = Board.find(params[:id])
    gon.board = @board

    @users = params[:board][:users].map do |username|
      User.find_by_username(username)
    end.compact

    if @users.present? && @users.length > 1
      @board = board.update_attributes(:title => params[:board][:title])
      @users.each do |user|
        board.users << user
      end
    else
      @board = board.update_attributes(:title => params[:board][:title])
      board.users << @users
    end

    render :json => {board: board, users: board.users}, status: 201
  end

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/show.html.erb
  <div class="preloader"></div>
  <div class="mobile-nav-container">

    <div class="mobile-nav-bar">

        <button type="button" class="btn-mobile-nav" data-toggle="collapse" data-target="#mobile-nav"></button>

      <!-- Mobile Logo -->
      <div class="logo-image">
        <a>
          <img src="<%= @user.avatar.url %>" alt=""/>
        </a>
      </div>

    </div>

    <!-- Mobile Drop Down -->
    <div id="mobile-nav" class="collapse">
      <ul>
         <li><%= link_to "All Boards", root_path %><br></li>
          <li class="dropdown"><a href="#">Add Pin</a>
            <ul class="sub-menu">
              <li><%= link_to "Add Image", new_board_pin_path(@board, @pin) %></li>
              <li><%= link_to "Add Text", new_board_text_pin_path(@board, @pin) %></li>
              <li><%= link_to "Add Link", new_board_link_path(@board, @link) %></li>
              <li><%= link_to "Add Quote", new_board_quote_path(@board, @quote) %></li>
            </ul>
          </li>
            <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>
  <!-- END Mobile Navigation -->

  <!-- BEGIN Side Nav -->
  <div class="side-nav">

    <!-- Side Nav Logo -->
    <div class="side-nav-logo">
      <a href="/">
        <img src="<%= @user.avatar.url %>" class="img-circle" alt=""/>
      </a>
    </div>

    <!-- Side Nav Text -->
    <div class="side-nav-bio">
      <h2 style="color: black;"><strong>Board:</strong><br /><%= @board.title %></h2>
    </div>

    <!-- Side Nav Menu -->
    <ul class="side-nav-menu">
      <li><%= link_to "All Boards", root_path %><br></li>
      <li class="dropdown"><a href="#">Add Pin</a>
        <ul class="sub-menu">
          <li><%= link_to "Add Image", new_board_pin_path(@board, @pin) %></li>
          <li><%= link_to "Add Text", new_board_text_pin_path(@board, @pin) %></li>
          <li><%= link_to "Add Link", new_board_link_path(@board, @link) %></li>
          <li><%= link_to "Add Quote", new_board_quote_path(@board, @quote) %></li>
        </ul>
      </li>
        <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
    </ul>

    <!-- Side Nav Widgets -->

    <!-- Side Nav Footer -->
    <div class="side-nav-footer">
      <p> Users on this board </p>
      <ul>
        <% @users.each do |user| %>
          </li><%= image_tag user.avatar.url, :id => "board_avatar", :title =>  user.username %></li>
          <% end %>
      </ul>
    </div>

  </div>

  <ul class="category-filter">
    <li><a href="#filter=" class="selected">All Posts</a></li>
    <li><a href="#filter=.audio">Audio</a></li>
    <li><a href="#filter=.image">Image</a></li>
    <li><a href="#filter=.link">Link</a></li>
    <li><a href="#filter=.quote">Quote</a></li>
    <li><a href="#filter=.standard">Standard</a></li>
    <li><a href="#filter=.video">Video</a></li>
  </ul>

  <div id="main-container">
    <div id="container">

      <%= render @all %>

    </div>
</div>