config/routes.rb
Tinytalk::Application.routes.draw do

  resources :comments, only: [:create, :edit, :update, :destroy]

  devise_for :users

  root to: "home#signin"

  match "index", to: "home#index"

  put "/update", to: "home#update"

  match 'boards/remove_user_from_board/:board_id/:user_id' => 'boards#remove_user_from_board'

  resources :boards do
    resources :pins
    resources :text_pins
    resources :links
    resources :quotes
  end

end

app/models/text_pin.rb
class TextPin < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :board_id

  belongs_to :user
  belongs_to :board

  validates :content, presence: true
  validates :title, presence: true

end

app/controllers/text_pins_controller.rb
class TextPinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  # GET /text_pins
  # GET /text_pins.json
  def index
    @board= Board.find(params[:board_id])
    @text_pins = @board.text_pins.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @text_pins }
    end
  end

  # GET /text_pins/1
  # GET /text_pins/1.json
  def show
    @user = current_user
    @text_pin = TextPin.find(params[:id])
    @board = Board.find(params[:board_id])
    @comment = Comment.new
    @comments = Comment.where(commentable_type: 'Text_Pin', commentable_id: @text_pin)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @text_pin }
    end
  end

  # GET /text_pins/new
  # GET /text_pins/new.json
  def new
    @board = Board.find(params[:board_id])
    @text_pin = current_user.text_pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @text_pin }
    end
  end

  # GET /text_pins/1/edit
  def edit
    @board = Board.find(params[:board_id])
    @text_pin = current_user.text_pins.find(params[:id])
  end

  # POST /text_pins
  # POST /text_pins.json
  def create
    @text_pin = current_user.text_pins.create(params[:text_pin])

    respond_to do |format|
      if @text_pin.save
        format.html { redirect_to "/boards/#{@text_pin.board_id}", notice: 'Text pin was successfully created.' }
        format.json { render json: @text_pin, status: :created, location: @text_pin }
      else
        format.html { render action: "new" }
        format.json { render json: @text_pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /text_pins/1
  # PUT /text_pins/1.json
  def update
    @board = Board.find(params[:board_id])
    @text_pin = current_user.text_pins.find(params[:id])

    respond_to do |format|
      if @text_pin.update_attributes(params[:text_pin])
        format.html { redirect_to board_text_pin_path(@board, @text_pin), notice: 'Text pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @text_pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_pins/1
  # DELETE /text_pins/1.json
  def destroy
    @board = params[:board_id]
    @text_pin = current_user.text_pins.find(params[:id])
    @text_pin.destroy

    respond_to do |format|
      format.html { redirect_to board_path(@board) }
      format.json { head :no_content }
    end
  end
end

app/helpers/text_pins_helper.rb
module TextPinsHelper
end

app/views/text_pins/_form.html.erb
<div id="main-container">
  <div class="container">
    <div class="span4">
      <!-- Page Title -->
      <div class="page-heading">
        <h1>Add Link</h1>
      </div>
      <!-- Alerts -->
      <div class="entry drop-shadow curved">
        <div class="contact-alerts">
      </div>
      <!-- Form -->
        <div class="row-fluid">
          <div class="span12">
            <%= simple_form_for([@board,@text_pin]) do |f| %>
              <%= f.error_notification %>
            <div class="form-inputs">
              <%= f.input :title %>
              <%= f.input :content %>
              <%= f.hidden_field :board_id, value: @board.id %>
            </div>
            <div class="form-actions">
              <%= f.button :submit %>
            </div>
          <% end %>
          </div>
          <%= link_to 'Back', board_path(@board) %>
        </div>
      </div>
    </div>
  </div>

app/views/text_pins/_text_pin.html.erb
      <div class="isotope-post span4 standard">
        <div>

            <div class="entry drop-shadow curved">

              <!-- Title -->
              <h5 class="heading">
                <%= link_to text_pin.title, board_text_pin_path(text_pin.board_id,text_pin.id)%></a>
              </h5>

              <!-- Content -->
              <p class="more"><%= text_pin.content %></p>

              <!-- Meta -->
              <ul class="entry-meta">
                <li class="time">Posted by <%= text_pin.user.email %></li><br>
                <li class="time">
                  <%= link_to "View Comments", board_text_pin_path(text_pin.board_id,text_pin.id)%>
                  (<%= Comment.where(commentable_type: "Text_Pin", commentable_id: "#{text_pin.id}").length %>)
                </li>
              </ul>

            </div>

        </div>
      </div>










<%
=begin %>
<div class="box">
  <strong><%= link_to (text_pin.title), board_text_pin_path(@board, text_pin) %></strong>

    <p class="description">
      <%= text_pin.content %>
    </p>
    <p>
      <strong>
        Posted by <%= text_pin.user.email %>
      </strong>
    </p>

    <% if current_user == text_pin.user %>
      <p>
        <%= link_to 'Edit', edit_board_text_pin_path(@board,text_pin) %>
        <%= link_to 'Destroy', board_text_pin_path(@board,text_pin), method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>
</div>
<%
=end %>

app/views/text_pins/edit.html.erb
<h1>Editing Text Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', board_text_pins_path(@board, @text_pin) %>

app/views/text_pins/index.html.erb
<div id="main-container">
    <div id="container">

      <% @text_pins.each do |pin| %>
      <div class="isotope-post span4 standard">
        <div>

            <div class="entry drop-shadow curved">

              <!-- Title -->
              <h5 class="heading">
                <%= link_to pin.title, board_text_pin_path(pin.board_id,pin.id)%></a>
              </h5>

              <!-- Content -->
              <p><%= pin.content %><%= link_to "Read More", board_text_pin_path(pin.board_id,pin.id)%></p>

              <!-- Meta -->
              <ul class="entry-meta">
                <li class="time">Posted by <%= pin.user.email %></li>
              </ul>

            </div>

        </div>
      </div>
      <% end %>


    </div>
  </div>

app/views/text_pins/new.html.erb
<h1>New text_pin</h1>

<%= render 'form' %>

app/views/text_pins/show.html.erb
<div class="preloader"></div>
  <div class="mobile-nav-container">

    <div class="mobile-nav-bar">

        <button type="button" class="btn-mobile-nav" data-toggle="collapse" data-target="#mobile-nav"></button>

      <!-- Mobile Logo -->
      <div class="logo-image">
        <a>
          <img src="<%= @user.avatar.url %>" alt=""/>
        </a>
      </div>

    </div>

    <!-- Mobile Drop Down -->
    <div id="mobile-nav" class="collapse">
      <ul>
         <li><%= link_to "All Boards", root_path %><br></li>
          <li class="dropdown"><a href="#">Add Pin</a>
            <ul class="sub-menu">
              <li><%= link_to "Add Image", new_board_pin_path(@board, @pin) %></li>
              <li><%= link_to "Add Text", new_board_text_pin_path(@board, @pin) %></li>
            </ul>
          </li>
            <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>
  <!-- END Mobile Navigation -->

  <!-- BEGIN Side Nav -->
  <div class="side-nav">

    <!-- Side Nav Logo -->
    <div class="side-nav-logo">
      <a href="/">
        <img src="<%= @user.avatar.url %>" class="img-circle" alt=""/>
      </a>
    </div>

    <!-- Side Nav Text -->
    <div class="side-nav-bio">
      <h2><strong>Board:</strong><%= @board.title %></h2>
    </div>

    <!-- Side Nav Menu -->
    <ul class="side-nav-menu">
      <li><%= link_to "Back", board_path(@board) %><br></li>
      <li class="dropdown"><a href="#">Add Pin</a>
        <ul class="sub-menu">
          <li><%= link_to "Add Image", new_board_pin_path(@board, @pin) %></li>
          <li><%= link_to "Add Text", new_board_text_pin_path(@board, @pin) %></li>
        </ul>
      </li>
        <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
    </ul>

    <!-- Side Nav Widgets -->
    <div class="side-nav-widget">
      <div class="side-nav-widget-inner">
        <ul>
          <li class="widget widget_search">
            <form role="search" method="get" id="searchform" action="#">
                <input type="text" placeholder="Search" value="" name="s" id="s" />
                <input type="submit" id="searchsubmit" value="Search" />
            </form>
          </li>
        </ul>
      </div>
    </div>

    <!-- Side Nav Footer -->
    <div class="side-nav-footer">
    </div>

  </div>


<p id="notice"><%= notice %></p>
<!DOCTYPE html>
<html lang="en-US">
<head>

    <meta charset="utf-8">

    <title>Spaces » Standard Post</title>

    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>

<body class="home blog">

  <!-- Grid -->
  <div id="main-container">
    <div class="container">

      <div class="row">
        <div class="span8 post-center">

            <div class="entry drop-shadow curved ">

              <!-- Title -->
              <h1 class="heading"><%=@text_pin.title %></h1>

              <!-- Content -->
              <p><%=@text_pin.content %></p>

              <!-- Comments -->
              <div id="allcomments">
              <ul class="entry-meta">
                <h2 class="heading">Comments</h2>
                <% @comments.each do |comment| %>
                  <li id="comment<%= comment.id %>">
                    <p>
                      <strong><%= User.find(comment.user_id).username %></strong>: <%= comment.content %>
                      <button data-id="<%= comment.id  %>" data-method="commdelete">Delete</button>
                    </p>
                  </li><br>
                <% end %>
              </ul><br>
              </div> <!-- Closing All Comments -->

              <!-- New Comments -->
              <%= form_for @comment do |f| %>
                <%= f.text_area :content, placeholder: "Enter Comment Here" %>
                <%= f.hidden_field :commentable_type, value: "Text_Pin" %>
                <%= f.hidden_field :commentable_id, value: @text_pin.id %>
                <%= f.hidden_field :board_id, value: @board.id %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.submit 'Submit Comment', id: "commentsubmit" %>
              <% end %>

              <!-- Meta -->
              <ul class="entry-meta">
                <li class="time">1 month ago</li>
              </ul>

          </div>

        </div>
      </div>

    </div>
  </div>

  <div class="mobile-footer">
    <ul>
      <li>
        <a href="#" rel="alternate" data-original-title="Pinterest"><img height="24" src="img/icons/glyphicons_360_pinterest@2x.png" alt="" /></a>
      </li>

      <li>
        <a href="#" rel="alternate" data-original-title="LinkedIn"><img height="24" src="img/icons/glyphicons_377_linked_in@2x.png" alt="" /></a>
      </li>

      <li>
        <a href="#" rel="alternate" data-original-title="Twitter"><img height="24" src="img/icons/glyphicons_392_twitter@2x.png" alt="" /></a>
      </li>

      <li>
        <a href="#" rel="alternate" data-original-title="Facebook"><img height="24" src="img/icons/glyphicons_390_facebook@2x.png" alt="" /></a>
      </li>

      <li>
        <a href="#" rel="alternate" data-original-title="Dribbble"><img height="24" src="img/icons/glyphicons_374_dribbble@2x.png" alt="" /></a>
      </li>

    </ul>
    <p>This is some awesome copyright text</p>
  </div>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  </body>
</html>